line-length = 120
target-version = "py311"

[lint]
select = ["E", "F", "I", "W"]

[lint.isort]
known-first-party = ["src", "scripts"]
split-on-trailing-comma = false

[format]
skip-magic-trailing-comma = true
